# Generated by Django 4.0.4 on 2022-06-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almuerzo',
            name='time',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bowl',
            name='time',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='time',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='desayuno',
            name='time',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='handroll',
            name='time',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='handrollready',
            name='time',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='kai',
            name='time',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='selladitas',
            name='time',
            field=models.FloatField(default=0, null=True),
        ),
    ]
